### ISSUE TITLE
Manage *all* Firewall Filters with Terraform?

### ISSUE THREAD

**Issue by Nornode** [terraform-routeros/terraform-provider-routeros#321]
**Is your feature request related to a problem? Please describe.**
Yes, Managed all Filters with terraform
I'm missing a clear and consise way of managing all firewall filters (and soon other parts too?) through Terraform.

**Describe the solution you'd like**
With an input variable I'd like to manage all firewall filters. 
e.g.

``` yaml 
---

firewall_filters:
  special_dummy_rule_to_show_fasttrack_counters:
    disabled: false
    action: "passthrough"
    chain: "forward"
    comment: "Default Config"

  defconf input accept established related untracked:
    disabled: false
    action: "accept"
    chain: "input"
    connection_state: "established,related,untracked"
    hw_offload: false
    priority: 0
    random: 0
    comment: "Default Config"
    place_before: "defconf input drop invalid"

  defconf input drop invalid:
    disabled: false
    chain: "input"  
    action: "drop"
    connection_state: "invalid"
    place_before: "defconf accept ICMP"
    
  defconf accept ICMP:
    disabled: false
    chain: "input"
    action: "accept"
    protocol: "icmp"
    comment: "Default Config - Allow ICMP"
    hw_offload: false
    place_before: "defconf accept to local loopback CAPsMAN"
```

Placing another custom rule in between one rule or last, I'd wish for the module/resource to arrange the rules in order on the router.

I don't know if this is really something that is possible or even possible?
I guess it would case many re-creates and potentially also locking out access during re-creates... ? 

**Additional context**
